### ISSUE TITLE
Kraken development tracker

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS#1180]
- [ ] storing logos  and readmes of extensions offline
    - #1640
 - [ ] better handling of killing/starting extensions
 - [x] progress bar/text for docker pull
 - [x] updating extensions (#1284)
 - [ ] automatically pick latest version (this is probably happening "automatically" due to how docker returns most recent tags first. not ideal)
 - [ ] checking requirements
 - [x] filtering tags for semver only?
 - [x] better formatting for permissions/settings (#1187 )
 - [ ] management of "un-managed" dockers (yes, I read that)
    - #2326 
    - #2327 
    - #2365
 - [ ] tests
 - [ ] check for disk space
 - [ ] failure handling (extension fails to start properly)
 - [x] log
 - [x] switch store/installed
 - [x] nice store icon on the store tab https://github.com/bluerobotics/BlueOS-docker/pull/1196
 - [x] cleanup unused images https://github.com/bluerobotics/BlueOS-docker/pull/1197
 - [x] allow not having a register_service file
 - [x] #1614
 - [x] Allow using 3rd party repositories (#1219)
