### ISSUE TITLE
[Tracking] Add missing aarch64 binaries

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS#2671]
bridges
- [x] binary is available: https://github.com/patrickelectric/bridges/pull/14
- [ ] added to BlueOS

filebrowser
- [x] binary is available: [yes, since 2.29.0](https://github.com/filebrowser/filebrowser/releases/download/v2.30.0/linux-386-filebrowser.tar.gz)
- [ ] added to BlueOS

linux2rest
- [x] binary is available: [yes](https://github.com/patrickelectric/linux2rest/releases/download/v0.6.0/linux2rest-aarch64-unknown-linux-gnu)
- [ ] added to BlueOS

machineid-cli
- [x] binary is available: https://github.com/patrickelectric/machineid-cli/pull/1
- [ ] added to BlueOS

mavlink_camera_manager
- [x] binary is available: [yes](https://github.com/mavlink/mavlink-camera-manager/releases/download/t3.13.1/mavlink-camera-manager-aarch64)
- [x] added to BlueOS: https://github.com/bluerobotics/BlueOS/pull/2669

mavlink_router
- [x] binary is available: [yes](https://github.com/mavlink-router/mavlink-router/releases/download/v4/mavlink-routerd-glibc-aarch64)
- [x] added to BlueOS: #2684

mavlink2rest
- [x] binary is available: https://github.com/mavlink/mavlink2rest/pull/106
- [x] added to BlueOS: https://github.com/bluerobotics/BlueOS/pull/2672

mavp2p
- [x] binary is available: [yes](https://github.com/bluenviron/mavp2p/releases/download/v1.2.1/mavp2p_v1.2.1_linux_arm64v8.tar.gz)
- [ ] added to BlueOS

ttyd
- [x] binary is available: [yes](https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd.aarch64)
- [ ] added to BlueOS
